[package]
name = "netkraken"
version = "0.1.7"
edition = "2021"

[[bin]]
name = "nk"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["derive"] }
ctrlc = "3.4.0"
# num_cpus = "1.16.0"
futures = "0.3.28"
serde = "1.0.181"
serde_derive = "1.0.181"
serde_json = "1.0.104"
tabled = "0.14.0"
tokio = { version = "1.32.0", features = ["full"] }
tokio-stream = "0.1.14"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
tracing-appender = "0.2.2"
time = "0.3.25"
uuid = { version = "1.4.1", features = ["v4", "fast-rng"] }
