[package]
name = "netkraken"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nk"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["derive"] }
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
time = "0.3.25"
